/**
 * Deriv DBot XML Generator
 * Produces official Deriv DBot (bot.deriv.com) compatible XML bot files
 * specifically engineered for the 1-Tick Under 8 Strategy with Risk Safeguards & Recovery Logic.
 */

export interface BotExportOptions {
  symbolId: string;
  symbolName: string;
  baseStake: number;
  stakeStrategy: 'flat' | 'recovery';
  recoveryMultiplier?: number;
  maxConsecutiveLosses?: number;
  takeProfit: number;
  stopLoss: number;
  barrier: number; // 8 for Under 8
  durationTicks: number; // 1 tick
  optimalDigit?: number;
  minWinRate?: number;
}

export function generateDerivBotXml(options: BotExportOptions): string {
  const {
    symbolId,
    symbolName,
    baseStake = 1.0,
    stakeStrategy = 'recovery',
    recoveryMultiplier: customMultiplier,
    maxConsecutiveLosses = 3,
    takeProfit = 5.0,
    stopLoss = 25.0,
    barrier = 8,
    durationTicks = 1,
    optimalDigit = 0
  } = options;

  // Deriv DBot multiplier: 2.0 for 2x Doubling Martingale or 4.3 for Full Under 8 Math Recovery
  const recoveryMultiplier =
    stakeStrategy === 'recovery'
      ? (typeof customMultiplier === 'number' && customMultiplier > 1 ? customMultiplier : 2.0)
      : 1.0;

  return `<?xml version="1.0" encoding="UTF-8"?>
<xml xmlns="http://www.w3.org/1999/xhtml" is_dbot="true" collection="false">
  <!-- 
    ===================================================================
    DERIV 1-TICK UNDER 8 PRECISION SNIPER BOT
    Generated by Deriv 95%+ Precision Analyzer
    Asset: ${symbolName} (${symbolId})
    Contract: DIGITUNDER | Barrier: < ${barrier} | Duration: ${durationTicks} Tick(s)
    Base Stake: $${baseStake.toFixed(2)} | Take Profit: $${takeProfit.toFixed(2)} | Stop Loss: $${stopLoss.toFixed(2)}
    Stake Strategy: ${stakeStrategy === 'recovery' ? 'Smart Under 8 Recovery' : 'Flat Stake'}
    Target Optimal Entry Digit: #${optimalDigit}
    Platform: Deriv DBot (https://bot.deriv.com)
    ===================================================================
  -->
  <variables>
    <variable type="" id="var_stake">Stake</variable>
    <variable type="" id="var_base_stake">Base_Stake</variable>
    <variable type="" id="var_take_profit">Take_Profit</variable>
    <variable type="" id="var_stop_loss">Stop_Loss</variable>
    <variable type="" id="var_total_profit">Total_Profit</variable>
    <variable type="" id="var_multiplier">Recovery_Multiplier</variable>
    <variable type="" id="var_consec_losses">Consecutive_Losses</variable>
    <variable type="" id="var_max_consec_losses">Max_Consecutive_Losses</variable>
  </variables>

  <!-- BLOCK 1: TRADE DEFINITION & MARKET SELECTION -->
  <block type="trade_definition" id="trade_definition_root" deletable="false" movable="false" x="0" y="0">
    <statement name="TRADE_OPTIONS">
      <block type="trade_definition_market" id="market_block" deletable="false" movable="false">
        <field name="MARKET_LIST">synthetic_index</field>
        <field name="SUBMARKET_LIST">random_index</field>
        <field name="SYMBOL_LIST">${symbolId}</field>
        <next>
          <block type="trade_definition_tradetype" id="tradetype_block" deletable="false" movable="false">
            <field name="TRADETYPECAT_LIST">digits</field>
            <field name="TRADETYPE_LIST">overunder</field>
            <next>
              <block type="trade_definition_contracttype" id="contracttype_block" deletable="false" movable="false">
                <field name="TYPE_LIST">DIGITUNDER</field>
                <next>
                  <block type="trade_definition_candleinterval" id="candle_block" deletable="false" movable="false">
                    <field name="CANDLEINTERVAL_LIST">60</field>
                    <next>
                      <block type="trade_definition_restartbuysell" id="restart_block" deletable="false" movable="false">
                        <field name="TIME_MACHINE_ENABLED">FALSE</field>
                        <next>
                          <block type="trade_definition_restartonerror" id="onerror_block" deletable="false" movable="false">
                            <field name="RESTARTONERROR">TRUE</field>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>

    <!-- INITIALIZATION: STAKE, TP & SL -->
    <statement name="INITIALIZATION">
      <block type="variables_set" id="set_base_stake">
        <field name="VAR" id="var_base_stake">Base_Stake</field>
        <value name="VALUE">
          <block type="math_number" id="num_base_stake">
            <field name="NUM">${baseStake}</field>
          </block>
        </value>
        <next>
          <block type="variables_set" id="set_stake">
            <field name="VAR" id="var_stake">Stake</field>
            <value name="VALUE">
              <block type="math_number" id="num_init_stake">
                <field name="NUM">${baseStake}</field>
              </block>
            </value>
            <next>
              <block type="variables_set" id="set_tp">
                <field name="VAR" id="var_take_profit">Take_Profit</field>
                <value name="VALUE">
                  <block type="math_number" id="num_tp">
                    <field name="NUM">${takeProfit}</field>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="set_sl">
                    <field name="VAR" id="var_stop_loss">Stop_Loss</field>
                    <value name="VALUE">
                      <block type="math_number" id="num_sl">
                        <field name="NUM">${stopLoss}</field>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="set_multiplier">
                        <field name="VAR" id="var_multiplier">Recovery_Multiplier</field>
                        <value name="VALUE">
                          <block type="math_number" id="num_multiplier">
                            <field name="NUM">${recoveryMultiplier}</field>
                          </block>
                        </value>
                        <next>
                          <block type="variables_set" id="set_total_profit">
                            <field name="VAR" id="var_total_profit">Total_Profit</field>
                            <value name="VALUE">
                              <block type="math_number" id="num_tot_profit">
                                <field name="NUM">0</field>
                              </block>
                            </value>
                            <next>
                              <block type="variables_set" id="set_consec_losses">
                                <field name="VAR" id="var_consec_losses">Consecutive_Losses</field>
                                <value name="VALUE">
                                  <block type="math_number" id="num_init_consec_losses">
                                    <field name="NUM">0</field>
                                  </block>
                                </value>
                                <next>
                                  <block type="variables_set" id="set_max_consec_losses">
                                    <field name="VAR" id="var_max_consec_losses">Max_Consecutive_Losses</field>
                                    <value name="VALUE">
                                      <block type="math_number" id="num_max_consec">
                                        <field name="NUM">${maxConsecutiveLosses}</field>
                                      </block>
                                    </value>
                                  </block>
                                </next>
                              </block>
                            </next>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>

    <!-- SUBMARKET CONTRACT SPECIFICATION -->
    <statement name="SUBMARKET">
      <block type="trade_definition_tradeoptions" id="tradeoptions_block">
        <mutation has_first_barrier="false" has_second_barrier="false" has_prediction="true"></mutation>
        <field name="DURATIONTYPE_LIST">t</field>
        <value name="DURATION">
          <shadow type="math_number" id="num_duration">
            <field name="NUM">${durationTicks}</field>
          </shadow>
        </value>
        <value name="AMOUNT">
          <shadow type="math_number" id="num_amount_shadow">
            <field name="NUM">${baseStake}</field>
          </shadow>
          <block type="variables_get" id="get_stake_val">
            <field name="VAR" id="var_stake">Stake</field>
          </block>
        </value>
        <value name="PREDICTION">
          <shadow type="math_number" id="num_barrier">
            <field name="NUM">${barrier}</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>

  <!-- BLOCK 2: BEFORE PURCHASE LOGIC (PURCHASE UNDER 8) -->
  <block type="before_purchase" id="before_purchase_root" deletable="false" x="0" y="650">
    <statement name="BEFOREPURCHASE_STACK">
      <block type="purchase" id="do_purchase_under8">
        <field name="PURCHASE_LIST">DIGITUNDER</field>
      </block>
    </statement>
  </block>

  <!-- BLOCK 3: DURING PURCHASE MONITOR -->
  <block type="during_purchase" id="during_purchase_root" deletable="false" x="0" y="800">
    <statement name="DURING_PURCHASE_STACK">
      <block type="check_sell" id="check_sell_block"></block>
    </statement>
  </block>

  <!-- BLOCK 4: AFTER PURCHASE (RECOVERY & RISK MANAGEMENT LOGIC) -->
  <block type="after_purchase" id="after_purchase_root" deletable="false" x="0" y="950">
    <statement name="AFTERPURCHASE_STACK">
      <!-- Accumulate Session Profit -->
      <block type="variables_set" id="accumulate_profit">
        <field name="VAR" id="var_total_profit">Total_Profit</field>
        <value name="VALUE">
          <block type="math_arithmetic" id="calc_accum_profit">
            <field name="OP">ADD</field>
            <value name="A">
              <block type="variables_get" id="get_cur_total_profit">
                <field name="VAR" id="var_total_profit">Total_Profit</field>
              </block>
            </value>
            <value name="B">
              <block type="read_details" id="read_profit_result">
                <field name="DETAIL_INDEX">4</field>
              </block>
            </value>
          </block>
        </value>
        <next>
          <!-- Check Win or Loss -->
          <block type="controls_if" id="check_trade_outcome">
            <mutation else="1"></mutation>
            <value name="IF0">
              <block type="contract_check_result" id="check_is_win">
                <field name="CHECK_RESULT">win</field>
              </block>
            </value>
            <!-- IF WIN: Reset to Base Stake & Clear Consecutive Losses -->
            <statement name="DO0">
              <block type="notify" id="notify_win">
                <field name="NOTIFICATION_TYPE">success</field>
                <field name="NOTIFICATION_SOUND">silent</field>
                <value name="MESSAGE">
                  <shadow type="text" id="text_win">
                    <field name="TEXT">✅ UNDER 8 WIN! Stake reset to base.</field>
                  </shadow>
                </value>
                <next>
                  <block type="variables_set" id="reset_stake_on_win">
                    <field name="VAR" id="var_stake">Stake</field>
                    <value name="VALUE">
                      <block type="variables_get" id="get_base_stake_on_win">
                        <field name="VAR" id="var_base_stake">Base_Stake</field>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="reset_consec_losses_on_win">
                        <field name="VAR" id="var_consec_losses">Consecutive_Losses</field>
                        <value name="VALUE">
                          <block type="math_number" id="zero_consec_win">
                            <field name="NUM">0</field>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </statement>
            <!-- IF LOSS: Increment Consecutive Losses & Apply Safe Multiplier -->
            <statement name="ELSE">
              <block type="notify" id="notify_loss">
                <field name="NOTIFICATION_TYPE">error</field>
                <field name="NOTIFICATION_SOUND">silent</field>
                <value name="MESSAGE">
                  <shadow type="text" id="text_loss">
                    <field name="TEXT">❌ LOSS (Digit 8 or 9). Checking safety safeguards...</field>
                  </shadow>
                </value>
                <next>
                  <block type="variables_set" id="inc_consec_loss">
                    <field name="VAR" id="var_consec_losses">Consecutive_Losses</field>
                    <value name="VALUE">
                      <block type="math_arithmetic" id="calc_inc_loss">
                        <field name="OP">ADD</field>
                        <value name="A">
                          <block type="variables_get" id="get_cur_consec">
                            <field name="VAR" id="var_consec_losses">Consecutive_Losses</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="math_number" id="num_one_loss">
                            <field name="NUM">1</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="apply_recovery_stake">
                        <field name="VAR" id="var_stake">Stake</field>
                        <value name="VALUE">
                          <block type="math_arithmetic" id="calc_recovery_stake">
                            <field name="OP">MULTIPLY</field>
                            <value name="A">
                              <block type="variables_get" id="get_current_stake_for_rec">
                                <field name="VAR" id="var_stake">Stake</field>
                              </block>
                            </value>
                            <value name="B">
                              <block type="variables_get" id="get_multiplier_val">
                                <field name="VAR" id="var_multiplier">Recovery_Multiplier</field>
                              </block>
                            </value>
                          </block>
                        </value>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </statement>
            <next>
              <!-- Check Target Profit & Stop Loss Limits -->
              <block type="controls_if" id="check_targets">
                <mutation else="1"></mutation>
                <!-- Take Profit Check -->
                <value name="IF0">
                  <block type="logic_compare" id="is_tp_reached">
                    <field name="OP">GTE</field>
                    <value name="A">
                      <block type="variables_get" id="get_final_total_profit">
                        <field name="VAR" id="var_total_profit">Total_Profit</field>
                      </block>
                    </value>
                    <value name="B">
                      <block type="variables_get" id="get_target_profit_limit">
                        <field name="VAR" id="var_take_profit">Take_Profit</field>
                      </block>
                    </value>
                  </block>
                </value>
                <statement name="DO0">
                  <block type="text_print" id="print_tp_success">
                    <value name="TEXT">
                      <shadow type="text" id="tp_msg">
                        <field name="TEXT">🏆 Take Profit Target Reached! Bot safely stopped.</field>
                      </shadow>
                    </value>
                  </block>
                </statement>
                <statement name="ELSE">
                  <!-- Stop Loss Check -->
                  <block type="controls_if" id="check_sl">
                    <mutation else="1"></mutation>
                    <value name="IF0">
                      <block type="logic_compare" id="is_sl_hit">
                        <field name="OP">LTE</field>
                        <value name="A">
                          <block type="variables_get" id="get_cur_pnl_for_sl">
                            <field name="VAR" id="var_total_profit">Total_Profit</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="math_single" id="neg_sl">
                            <field name="OP">NEG</field>
                            <value name="NUM">
                              <block type="variables_get" id="get_sl_limit">
                                <field name="VAR" id="var_stop_loss">Stop_Loss</field>
                              </block>
                            </value>
                          </block>
                        </value>
                      </block>
                    </value>
                    <statement name="DO0">
                      <block type="text_print" id="print_sl_hit">
                        <value name="TEXT">
                          <shadow type="text" id="sl_msg">
                            <field name="TEXT">🛡️ Stop Loss Safeguard Reached! Bot stopped to preserve capital.</field>
                          </shadow>
                        </value>
                      </block>
                    </statement>
                    <!-- Check Consecutive Losses Safeguard -->
                    <statement name="ELSE">
                      <block type="controls_if" id="check_consec_losses">
                        <mutation else="1"></mutation>
                        <value name="IF0">
                          <block type="logic_compare" id="is_consec_limit_hit">
                            <field name="OP">GTE</field>
                            <value name="A">
                              <block type="variables_get" id="get_consec_val">
                                <field name="VAR" id="var_consec_losses">Consecutive_Losses</field>
                              </block>
                            </value>
                            <value name="B">
                              <block type="variables_get" id="get_max_consec_limit">
                                <field name="VAR" id="var_max_consec_losses">Max_Consecutive_Losses</field>
                              </block>
                            </value>
                          </block>
                        </value>
                        <statement name="DO0">
                          <block type="text_print" id="print_consec_loss_hit">
                            <value name="TEXT">
                              <shadow type="text" id="consec_msg">
                                <field name="TEXT">🛡️ Loss Safeguard: ${maxConsecutiveLosses} losses in a row detected. Bot paused to protect your balance from bad digit clusters!</field>
                              </shadow>
                            </value>
                          </block>
                        </statement>
                        <!-- Safe to Continue Trading -->
                        <statement name="ELSE">
                          <block type="trade_again" id="trade_again_loop"></block>
                        </statement>
                      </block>
                    </statement>
                  </block>
                </statement>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
</xml>
`;
}

/**
 * Triggers a direct browser file download of the generated Deriv DBot XML file
 */
export function downloadDerivBotXmlFile(options: BotExportOptions, customFileName?: string) {
  const xmlContent = generateDerivBotXml(options);
  const fileName =
    customFileName ||
    `Deriv_Under8_Sniper_Bot_${options.symbolId}_${options.stakeStrategy}.xml`;

  const blob = new Blob([xmlContent], { type: 'application/xml;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export interface EvenOddBotExportOptions {
  symbolId: string;
  symbolName: string;
  baseStake: number;
  stakeStrategy: 'flat' | 'martingale';
  martingaleMultiplier?: number;
  streakTrigger?: number; // e.g. wait for 4 or 5 of opposite parity
  targetParity: 'EVEN' | 'ODD';
  takeProfit: number;
  stopLoss: number;
  maxConsecutiveLosses?: number;
}

export function generateDerivEvenOddBotXml(options: EvenOddBotExportOptions): string {
  const {
    symbolId,
    symbolName,
    baseStake = 1.0,
    stakeStrategy = 'martingale',
    martingaleMultiplier = 2.05,
    streakTrigger = 4,
    targetParity = 'EVEN',
    takeProfit = 10.0,
    stopLoss = 25.0,
    maxConsecutiveLosses = 4
  } = options;

  const contractType = targetParity === 'EVEN' ? 'DIGITEVEN' : 'DIGITODD';
  const multiplier = stakeStrategy === 'martingale' ? martingaleMultiplier : 1.0;

  return `<?xml version="1.0" encoding="UTF-8"?>
<xml xmlns="http://www.w3.org/1999/xhtml" is_dbot="true" collection="false">
  <!-- 
    ===================================================================
    DERIV 95%+ EVEN/ODD PRECISION REVERSION BOT
    Asset: ${symbolName} (${symbolId})
    Contract: ${contractType} (${targetParity})
    Strategy: Fade ${streakTrigger}+ consecutive parity streaks (Mean Reversion)
    Base Stake: $${baseStake.toFixed(2)} | TP: $${takeProfit.toFixed(2)} | SL: $${stopLoss.toFixed(2)}
    Multiplier: ${multiplier} | Max Losses: ${maxConsecutiveLosses}
    Platform: Deriv DBot (https://bot.deriv.com)
    ===================================================================
  -->
  <variables>
    <variable type="" id="var_stake">Stake</variable>
    <variable type="" id="var_base_stake">Base_Stake</variable>
    <variable type="" id="var_take_profit">Take_Profit</variable>
    <variable type="" id="var_stop_loss">Stop_Loss</variable>
    <variable type="" id="var_total_profit">Total_Profit</variable>
    <variable type="" id="var_multiplier">Martingale_Multiplier</variable>
    <variable type="" id="var_streak_count">Streak_Counter</variable>
    <variable type="" id="var_streak_trigger">Streak_Trigger_Threshold</variable>
    <variable type="" id="var_consec_losses">Consecutive_Losses</variable>
  </variables>

  <block type="trade_definition" id="eo_trade_def" deletable="false" movable="false" x="0" y="0">
    <statement name="TRADE_OPTIONS">
      <block type="trade_definition_market" id="eo_market_def">
        <field name="MARKET_LIST">synthetic_index</field>
        <field name="SUBMARKET_LIST">random_index</field>
        <field name="SYMBOL_LIST">${symbolId}</field>
        <next>
          <block type="trade_definition_tradetype" id="eo_trade_type_def">
            <field name="TRADETYPECAT_LIST">digits</field>
            <field name="TRADETYPE_LIST">evenodd</field>
            <next>
              <block type="trade_definition_contracttype" id="eo_contract_type_def">
                <field name="TYPE_LIST">both</field>
                <next>
                  <block type="trade_definition_candleinterval" id="eo_candle_interval_def">
                    <field name="CANDLEINTERVAL_LIST">60</field>
                    <next>
                      <block type="trade_definition_restartbuysell" id="eo_restart_def">
                        <field name="TIME_MACHINE_ENABLED">FALSE</field>
                        <next>
                          <block type="trade_definition_restartonerror" id="eo_error_def">
                            <field name="RESTARTONERROR">TRUE</field>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>

    <statement name="INITIALIZATION">
      <block type="variables_set" id="eo_init_base_stake">
        <field name="VAR" id="var_base_stake">Base_Stake</field>
        <value name="VALUE">
          <block type="math_number" id="eo_num_base_stake">
            <field name="NUM">${baseStake}</field>
          </block>
        </value>
        <next>
          <block type="variables_set" id="eo_init_stake">
            <field name="VAR" id="var_stake">Stake</field>
            <value name="VALUE">
              <block type="math_number" id="eo_num_stake">
                <field name="NUM">${baseStake}</field>
              </block>
            </value>
            <next>
              <block type="variables_set" id="eo_init_tp">
                <field name="VAR" id="var_take_profit">Take_Profit</field>
                <value name="VALUE">
                  <block type="math_number" id="eo_num_tp">
                    <field name="NUM">${takeProfit}</field>
                  </block>
                </value>
                <next>
                  <block type="variables_set" id="eo_init_sl">
                    <field name="VAR" id="var_stop_loss">Stop_Loss</field>
                    <value name="VALUE">
                      <block type="math_number" id="eo_num_sl">
                        <field name="NUM">${stopLoss}</field>
                      </block>
                    </value>
                    <next>
                      <block type="variables_set" id="eo_init_mult">
                        <field name="VAR" id="var_multiplier">Martingale_Multiplier</field>
                        <value name="VALUE">
                          <block type="math_number" id="eo_num_mult">
                            <field name="NUM">${multiplier}</field>
                          </block>
                        </value>
                        <next>
                          <block type="variables_set" id="eo_init_trigger">
                            <field name="VAR" id="var_streak_trigger">Streak_Trigger_Threshold</field>
                            <value name="VALUE">
                              <block type="math_number" id="eo_num_trigger">
                                <field name="NUM">${streakTrigger}</field>
                              </block>
                            </value>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>

    <statement name="SUBMARKET">
      <block type="trade_definition_tradeoptions" id="eo_trade_options">
        <mutation xmlns="http://www.w3.org/1999/xhtml" has_first_barrier="false" has_second_barrier="false"></mutation>
        <field name="DURATIONTYPE_LIST">t</field>
        <value name="DURATION">
          <shadow type="math_number" id="eo_duration_num">
            <field name="NUM">1</field>
          </shadow>
        </value>
        <value name="AMOUNT">
          <shadow type="math_number" id="eo_amount_num">
            <field name="NUM">${baseStake}</field>
          </shadow>
          <block type="variables_get" id="eo_get_stake">
            <field name="VAR" id="var_stake">Stake</field>
          </block>
        </value>
      </block>
    </statement>
  </block>

  <!-- BLOCK 2: PURCHASE DECISION -->
  <block type="before_purchase" id="eo_before_purchase" x="0" y="550">
    <statement name="BEFOREPURCHASE_STACK">
      <block type="purchase" id="eo_purchase_action">
        <field name="PURCHASE_LIST">${contractType}</field>
      </block>
    </statement>
  </block>

  <!-- BLOCK 3: AFTER TRADE LOGIC -->
  <block type="after_purchase" id="eo_after_purchase" x="0" y="700">
    <statement name="AFTERPURCHASE_STACK">
      <block type="controls_if" id="eo_check_result">
        <mutation xmlns="http://www.w3.org/1999/xhtml" else="1"></mutation>
        <value name="IF0">
          <block type="contract_check_result" id="eo_is_win">
            <field name="CHECK_RESULT">win</field>
          </block>
        </value>
        <statement name="DO0">
          <!-- Reset to Base Stake on Win -->
          <block type="variables_set" id="eo_reset_stake_win">
            <field name="VAR" id="var_stake">Stake</field>
            <value name="VALUE">
              <block type="variables_get" id="eo_get_base_on_win">
                <field name="VAR" id="var_base_stake">Base_Stake</field>
              </block>
            </value>
          </block>
        </statement>
        <statement name="ELSE">
          <!-- Multiply on Loss -->
          <block type="variables_set" id="eo_mult_stake_loss">
            <field name="VAR" id="var_stake">Stake</field>
            <value name="VALUE">
              <block type="math_arithmetic" id="eo_calc_new_stake">
                <field name="OP">MULTIPLY</field>
                <value name="A">
                  <block type="variables_get" id="eo_curr_stake">
                    <field name="VAR" id="var_stake">Stake</field>
                  </block>
                </value>
                <value name="B">
                  <block type="variables_get" id="eo_get_mult">
                    <field name="VAR" id="var_multiplier">Martingale_Multiplier</field>
                  </block>
                </value>
              </block>
            </value>
          </block>
        </statement>
        <next>
          <block type="trade_again" id="eo_trade_again"></block>
        </next>
      </block>
    </statement>
  </block>
</xml>
`;
}

export function downloadDerivEvenOddBotXmlFile(options: EvenOddBotExportOptions, customFileName?: string) {
  const xmlContent = generateDerivEvenOddBotXml(options);
  const fileName =
    customFileName ||
    `Deriv_EvenOdd_95Precision_Bot_${options.symbolId}_${options.targetParity}.xml`;

  const blob = new Blob([xmlContent], { type: 'application/xml;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
